### ISSUE TITLE
Why does this fork exist

### ISSUE THREAD

**Issue by RobJN** [osm-uk/name-suggestion-index#5]
Hi. Can someone please explain to me why this fork exists. On the OSM wiki it says that:

> There is an OSMUK fork of the name-suggestion-index in the OSMUK git group account for making UK/GB changes and creating pull requests. Raise individual issues there and we will try to get them accepted into the system, or you can create your own fork.

I don't understand why we should not just raise pull requests against the upstream repo. Why the need for this fork?

Thanks.
p.s. this may just be me not understanding GitHib properly.

**Comment by jnicho02** [comment]
in order to create a pull request you must have a fork. You could have your own personal fork, or we could have a shared fork

**Comment by RobJN** [comment]
OK. I think what I normally do is create my own fork (or branch). If you use github web when you click to edit a file it does this fork/branch automatically. After the PR is accepted I usually delete my fork/branch.

Thanks anyway for explaining.
